### ISSUE TITLE
Subfolders are currently not supported

### ISSUE THREAD

**Issue by salusalpha** [CollinAlpert/MailSort#5]
Hi Collin...

to make this great tool really a killer subfolders would need to be supported in the typical IMAP format like eg "INBOX.SubFolder1.Subfolder2"

Additionally a date filter to work only on email younger than 30 days would be great to speed up on big email boxes.

thanks
sa

**Comment by CollinAlpert** [comment]
I managed to specify subfolders by using forward slashes. Can you try that?
